
format:
  html:
    theme: cosmo
    toc: false
    css:
      - styles.css
      - styles_nodes.css
      - trainings.css
    title-block: false
    include-before-body: landing-network.html




project:
  type: website
  output-dir: docs/

website:
  # title: "InforBio"
  # site-url: https://inforbio.github.io/
  favicon: images/logoInforBio_fond_blanc.png
  
  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/)"
    left: "&copy; CC BY-NC 4.0 [InforBio]"
    
  navbar:
    logo: images/logoInforBio_fond_blanc.png
    left:
      - href: index.qmd
        text: "About Us"
      - href: content/services.qmd
        text: "Services"
      - text: "Trainings"
        menu: 
          - text: "What is IOT?"
            href: content/what_is_iot.qmd
          - text: "IOT R & scRNAseq"
            href: content/iot_r_scrnaseq.qmd
          - text: "IOT Bulk RNAseq"
            href: content/iot_bulk_rnaseq.qmd
          - text: "2-Day R training"
            href: content/r2d_training.qmd
      - href: content/short_lectures.qmd
        text: "Mini-Talk Series"
      # - text: "News"
      #   href: content/news.qmd
      - icon: github
        href: https://github.com/InforBio/InforBio.github.io

link-external-newwindow: true
