---
title: "What is IOC?"
---

The **InforBio** platform has developed an "**Interactive Online Companionship**" (IOC)
specifically tailored to initiate researchers into bioinformatics.
The IOC involved one-to-many virtual work sessions where companions are trained to **analyze their own data**.

All IOC programs are structured into a series of modules,
with each module building upon the knowledge and skills acquired in the
previous one.
One module lasts one week, during which companions dive into **online materials**
to ensure they understand and internalize the content.
Companions then complete **quizzes and exercises** using both public and
their own data to gauge their understanding,
receiving **personalized feedback** on their work.
To facilitate their learning, we provide access to computational resources such as Rstudio and Galaxy servers.
The module wraps up with videoconference to recap
the week's material and address any questions.
These videoconferences are recorded and made available for later viewing,
ensuring continuous access to the learning resources.

By the end of an IOC, companions will be equipped with expertise and
confidence to run their own analyses independently.